---

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Copy ssh key
  copy:
    src: files/id_rsa
    dest: /home/devops/.ssh/
    owner: devops
    group: www-data
    mode: 0600
- copy:
    src: files/id_rsa.pub
    dest: /home/devops/.ssh/
    owner: devops
    group: www-data
    mode: 0644

- name: Create /var/www directory
  file: dest=/var/www/ state=directory owner=devops group=www-data mode=u=rwx,g=rx

- name: Create supervisor directory
  file: dest=/etc/supervisor/conf.d/ state=directory owner=root group=root mode=u=rwx,g=rwx,o=rx

- name: Clone git repository
  git: >
    dest=/var/www/current
    repo=git@github.com:Dirk94/crypto.git
    update=no
    accept_hostkey=yes
  become: yes
  become_user: devops

- name: Run composer install
  script: scripts/composer_install.sh
  become: yes
  become_user: devops

- name: Copy .env file
  template: src=templates/.env.tpl dest=/var/www/current/.env owner=devops group=www-data mode=0644

- name: Copy supervisor config
  template: src=templates/laravel-worker.conf dest=/etc/supervisor/conf.d/laravel-worker.conf owner=root group=root mode=0644

- name: Run migrations
  shell: php /var/www/current/artisan migrate --force

- name: Seed Database
  shell: php /var/www/current/artisan db:seed

- name: Set laravel file permissions
  file:
    path: /var/www/current/storage/logs/
    state: directory
    mode: u=rwx,g=rwx,o=rx
- file:
    path: /var/www/current/storage/framework/views
    state: directory
    mode: u=rwx,g=rwx,o=rx

- name: Create laravel.log file
  copy:
    content: ""
    dest: /var/www/current/storage/logs/laravel.log
    force: no
    owner: www-data
    group: www-data
    mode: u=rw,g=rw,o=r

- name: Create worker.log file
  copy:
    content: ""
    dest: /var/www/current/storage/logs/worker.log
    force: no
    owner: www-data
    group: www-data
    mode: u=rw,g=rw,o=r

- name: Configure nginx
  template: src=nginx.conf dest=/etc/nginx/sites-available/default
  notify:
  - restart php-fpm
  - restart nginx

- name: Start supervisor
  shell: supervisorctl reread
- shell: supervisorctl update
- shell: supervisorctl start laravel-worker:*

- name: Add laravel scheduler to cron
  cron:
    name: "laravel supervisor"
    job: php /var/www/current/artisan schedule:run >> /dev/null 2>&1
